import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import Image from "next/image";
import loisarn from '../public/Cartoonify.png'
import {useState} from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Louice Borg Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark: text-white">developedbyloisarn</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/></li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Louice Borg</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-x
            l mx-auto">Lorem Ipsum</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle/>
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={loisarn} layout="fill" objectFit="cover" />
          </div>
        </section>
        
        <section>
          <div>
            <h3 className="text-3xl py-2 text-center dark:text-white">Services</h3>
            <p className="text-md py-2 text-center leading-8 text-gray-800">Lorem Ipsum</p>
          </div>
          <div className="lg:flex gap-10 ">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <h4 className="py-4 text-teal-600">Design tools I use</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">ProCreate</p>
              <p className="text-gray-800 py-1">Photoshop</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <h4 className="py-4 text-teal-600">Technologies</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">ProCreate</p>
              <p className="text-gray-800 py-1">Photoshop</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <h4 className="py-4 text-teal-600">Languages</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">ProCreate</p>
              <p className="text-gray-800 py-1">Photoshop</p>
            </div>
          </div>
        </section>
        <section>
          <div className="flex flex-column gap-10 py-10 text-center lg:flex-row lg:flex-wrap">
            <h3 className="text-3xl py-1 text-center dark:text-white">Portfolio</h3>
            <p>Länka bilder här</p>
          </div>
          <div className="basis-1/3 flex-1">
            {/* <Image src={pic} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/> */}
          </div>
        </section>
      </main>
      </div>

  );
}
